CREATE TABLE AttendanceLog (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Auto-generated primary key
    StudentID VARCHAR2(50) NOT NULL,        -- Unique identifier for the student (no longer primary key)
    StudentName VARCHAR2(100) NOT NULL,     -- Name of the student
    InOut VARCHAR2(10) NOT NULL,            -- Status: "IN" or "OUT"
    Staff VARCHAR2(100) NOT NULL,           -- Staff member who scanned the record
    MacAddress VARCHAR2(17),                -- MAC address of the staff's phone
    ScanTimestamp TIMESTAMP DEFAULT SYSTIMESTAMP
);


INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12345', 'John Doe', 'IN', 'Jane Smith', '00:1B:44:11:3A:B7');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12346', 'Jane Doe', 'OUT', 'Alice Johnson', '00:1B:44:11:3A:B8');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12347', 'Michael Smith', 'IN', 'John Brown', '00:1B:44:11:3A:B9');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12348', 'Emily Davis', 'OUT', 'Sarah White', '00:1B:44:11:3A:C0');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12349', 'David Johnson', 'IN', 'David Green', '00:1B:44:11:3A:C1');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12350', 'Sophia Brown', 'IN', 'Robert Clark', '00:1B:44:11:3A:C2');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12351', 'Liam Miller', 'OUT', 'Daniel King', '00:1B:44:11:3A:C3');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12352', 'Olivia Wilson', 'IN', 'Emily Lee', '00:1B:44:11:3A:C4');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12353', 'Noah Moore', 'OUT', 'Jessica Adams', '00:1B:44:11:3A:C5');

INSERT INTO AttendanceLog (StudentID, StudentName, InOut, Staff, MacAddress)
VALUES ('12354', 'Ava Taylor', 'IN', 'Sophia Evans', '00:1B:44:11:3A:C6');


COMMIT