version: "3.8"

services:
  app:
    build:
      context: .                  # Use the Dockerfile in the current directory
    volumes:
      - .:/usr/src/app            # Mount the current directory to the container
      - /usr/src/app/node_modules # Avoid overwriting node_modules with the bind mount
    ports:
      - "3000:3000"               # Expose the app on port 3000
    environment:
      - NODE_ENV=development
      - DB_HOST=oracle-db
      - DB_PORT=1521
      - DB_USER=system
      - DB_PASSWORD=oracle
      - DB_SERVICE_NAME=XE
    depends_on:
      - oracle-db
    command: ["npm", "run", "start-dev"] # Run app with nodemon for live reload

  oracle-db:
    image: gvenzl/oracle-xe
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=oracle
    container_name: oracle-db
